name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # update setiap hari
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: AgungDev
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
